import { GrandPrix } from '../types';

export const F1_CALENDAR_2025: GrandPrix[] = [
  {
    id: 'australia',
    name: 'Gran Premio de Australia',
    country: 'Australia',
    circuit: 'Circuito de Albert Park',
    dates: '14-16 Mar',
    countryCode: 'AU',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/C5fmmWmh58Pp' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/K896sNv7Dr5V' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/I16qSGg8HeqV' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/s06UwLqJFw0N' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/NLjxpcuWe5LY' },
    ],
  },
  {
    id: 'china',
    name: 'Gran Premio de China',
    country: 'China',
    circuit: 'Circuito Internacional de Shanghái',
    dates: '21-23 Mar',
    countryCode: 'CN',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/48wYHC6W7KaA' },
      { name: 'Clasificación Sprint', videoUrl: 'https://video.eventoshq.me/f/jM35FtaGMirB' },
      { name: 'Carrera Sprint', videoUrl: 'https://video.eventoshq.me/f/3Id3Oy6CNvLy' },
      { name: 'Clasificación GP', videoUrl: 'https://video.eventoshq.me/f/arRPort9iDax' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/LXMS9lQf53PR' },
    ],
  },
  {
    id: 'japon',
    name: 'Gran Premio de Japón',
    country: 'Japón',
    circuit: 'Circuito de Suzuka',
    dates: '04-06 Abr',
    countryCode: 'JP',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/vwo4ShDnZRIx' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/wFcJOQDvext9' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/cNkQLX3Ij5CW' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/416YWSEzTRT2' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/O6PmlpdwBhIE' },
    ],
  },
  {
    id: 'barein',
    name: 'Gran Premio de Baréin',
    country: 'Baréin',
    circuit: 'Circuito Internacional de Baréin',
    dates: '11-13 Abr',
    countryCode: 'BH',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/dU9rak1kxzQE' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/sco2GTkPIe4D' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/OJDZmTweSxRV' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/416YWSEzTRT2' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/3rWgoF5j7T14' },
    ],
  },
  {
    id: 'arabia-saudita',
    name: 'Gran Premio de Arabia Saudita',
    country: 'Arabia Saudita',
    circuit: 'Circuito de la Corniche de Yeda',
    dates: '18-20 Abr',
    countryCode: 'SA',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/dQgicEvZzyYr' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/vzV4XVg3kAz2' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/4Sk1QuLIFQlQ' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/hjCNnCz1xh69' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/aClxoAx1882X' },
    ],
  },
  {
    id: 'miami',
    name: 'Gran Premio de Miami',
    country: 'EE. UU.',
    circuit: 'Autódromo Internacional de Miami',
    dates: '02-04 May',
    countryCode: 'US',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/jSdwNAKyhEmg' },
      { name: 'Clasificación Sprint', videoUrl: 'https://video.eventoshq.me/f/placeholder-mia-sq' },
      { name: 'Carrera Sprint', videoUrl: 'https://video.eventoshq.me/f/D8cngss125tb' },
      { name: 'Clasificación GP', videoUrl: 'https://video.eventoshq.me/f/mvIfJh3Vf5O7' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/4BtjntUY7Rmo' },
    ],
  },
  {
    id: 'emilia-romana',
    name: 'Gran Premio de Emilia-Romaña',
    country: 'Italia',
    circuit: 'Autodromo Enzo e Dino Ferrari (Imola)',
    dates: '16-18 May',
    countryCode: 'IT',
    mapId: 'git --version',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/4qCRWaj9x6Fi' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/cRu0bqzFJNIO' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/iuXG5xjLnJBM' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/HPEMwYrUB904' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/qYAYxrvbsILR' },
    ],
  },
  {
    id: 'monaco',
    name: 'Gran Premio de Mónaco',
    country: 'Mónaco',
    circuit: 'Circuito de Mónaco',
    dates: '23-25 May',
    countryCode: 'MC',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/q5QSHaKHQXxC' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/41yF29p1nn82' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/hBel1HTXbTKj' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/DC6ZdL06SMl6' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/9qTWFIMNMYuW' },
    ],
  },
  {
    id: 'espana',
    name: 'Gran Premio de España',
    country: 'España',
    circuit: 'Circuit de Barcelona-Catalunya',
    dates: '30 May-01 Jun',
    countryCode: 'ES',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/jbuIVVLM4XaR' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/KE7YgTopXqiX' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/sFWWVVsl3jPS' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/92ON3kWRE1K2' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/AoeFYfs8xQNL' },
    ],
  },
  {
    id: 'canada',
    name: 'Gran Premio de Canadá',
    country: 'Canadá',
    circuit: 'Circuito Gilles-Villeneuve',
    dates: '13-15 Jun',
    countryCode: 'CA',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/s5W0rdEOHPBa' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/5jL5DvnEWLN9' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/75vIUnyT8IaB' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/kpEp515kN7RC' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/fwhEIj2Dkm3Y' },
    ],
  },
  {
    id: 'austria',
    name: 'Gran Premio de Austria',
    country: 'Austria',
    circuit: 'Red Bull Ring',
    dates: '27-29 Jun',
    countryCode: 'AT',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/503qqgkmp1nY' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/pYp1QeeH7AD9' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/MLIqOwREdBaa' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/wUnK8MG4NOmU' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/qPjFl32yT9XV' },
    ],
  },
  {
    id: 'gran-bretana',
    name: 'Gran Premio de Gran Bretaña',
    country: 'Reino Unido',
    circuit: 'Circuito de Silverstone',
    dates: '04-06 Jul',
    countryCode: 'GB',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/iqBacFqphePR' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/0FH0d5VCcaMp' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/uKdWEV7szLf4' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/NorPV8Y1ks5O' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/9xwhmP82exUl' },
    ],
  },
  {
    id: 'belgica',
    name: 'Gran Premio de Bélgica',
    country: 'Bélgica',
    circuit: 'Circuito de Spa-Francorchamps',
    dates: '25-27 Jul',
    countryCode: 'BE',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/Vgrnf3ZAYDGU' },
      { name: 'Clasificación Sprint', videoUrl: 'https://video.eventoshq.me/f/VCprIIZxSBe4' },
      { name: 'Carrera Sprint', videoUrl: 'https://video.eventoshq.me/f/ntM0RAfEcsAO' },
      { name: 'Clasificación GP', videoUrl: 'https://video.eventoshq.me/f/R2E8AYiW0fdE' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/AxBDG4kLTDTu' },
    ],
  },
  {
    id: 'hungria',
    name: 'Gran Premio de Hungría',
    country: 'Hungría',
    circuit: 'Hungaroring',
    dates: '01-03 Ago',
    countryCode: 'HU',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/yv9GwqEU9v7M' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/BLtEQbU1QrJK' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/GiYq2fgJ6qj1' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/QaLyuPLN8Ik2' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/aVItKX1M0MHt' },
    ],
  },
  {
    id: 'paises-bajos',
    name: 'Gran Premio de Países Bajos',
    country: 'Países Bajos',
    circuit: 'Circuito Zandvoort',
    dates: '29-31 Ago',
    countryCode: 'NL',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/QhyLhi03ggjg' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/placeholder-nld-p2' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/50r529CiiDNh' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/86RQoRQKIcgm' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/lJCivoodlK8P' },
    ],
  },
  {
    id: 'italia',
    name: 'Gran Premio de Italia',
    country: 'Italia',
    circuit: 'Autodromo Nazionale Monza',
    dates: '05-07 Sep',
    countryCode: 'IT',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/VWzqLDD570Rv' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/placeholder-ita-p2' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/hmVYapXBRI4B' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/xhO7lGhVQMtk' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/7A4s0Ynsrfqf' },
    ],
  },
  {
    id: 'azerbaiyan',
    name: 'Gran Premio de Azerbaiyán',
    country: 'Azerbaiyán',
    circuit: 'Circuito callejero de Bakú',
    dates: '19-21 Sep',
    countryCode: 'AZ',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/placeholder-aze-p1' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/placeholder-aze-p2' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/placeholder-aze-p3' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/placeholder-aze-q' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/placeholder-aze-race' },
    ],
  },
  {
    id: 'singapur',
    name: 'Gran Premio de Singapur',
    country: 'Singapur',
    circuit: 'Circuito callejero de Marina Bay',
    dates: '03-05 Oct',
    countryCode: 'SG',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/placeholder-sgp-p1' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/placeholder-sgp-p2' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/placeholder-sgp-p3' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/placeholder-sgp-q' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/placeholder-sgp-race' },
    ],
  },
  {
    id: 'estados-unidos',
    name: 'Gran Premio de Estados Unidos',
    country: 'EE. UU.',
    circuit: 'Circuito de las Américas (Austin)',
    dates: '17-19 Oct',
    countryCode: 'US',
    mapId: 'us-austin',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/placeholder-usa-p1' },
      { name: 'Clasificación Sprint', videoUrl: 'https://video.eventoshq.me/f/placeholder-usa-sq' },
      { name: 'Carrera Sprint', videoUrl: 'https://video.eventoshq.me/f/placeholder-usa-sr' },
      { name: 'Clasificación GP', videoUrl: 'https://video.eventoshq.me/f/placeholder-usa-q' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/placeholder-usa-race' },
    ],
  },
  {
    id: 'mexico',
    name: 'Gran Premio de México',
    country: 'México',
    circuit: 'Autódromo Hermanos Rodríguez',
    dates: '24-26 Oct',
    countryCode: 'MX',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/placeholder-mex-p1' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/placeholder-mex-p2' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/placeholder-mex-p3' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/placeholder-mex-q' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/placeholder-mex-race' },
    ],
  },
  {
    id: 'brasil',
    name: 'Gran Premio de São Paulo',
    country: 'Brasil',
    circuit: 'Autódromo José Carlos Pace (Interlagos)',
    dates: '07-09 Nov',
    countryCode: 'BR',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/placeholder-bra-p1' },
      { name: 'Clasificación Sprint', videoUrl: 'https://video.eventoshq.me/f/placeholder-bra-sq' },
      { name: 'Carrera Sprint', videoUrl: 'https://video.eventoshq.me/f/placeholder-bra-sr' },
      { name: 'Clasificación GP', videoUrl: 'https://video.eventoshq.me/f/placeholder-bra-q' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/placeholder-bra-race' },
    ],
  },
  {
    id: 'las-vegas',
    name: 'Gran Premio de Las Vegas',
    country: 'EE. UU.',
    circuit: 'Circuito callejero de Las Vegas',
    dates: '20-22 Nov',
    countryCode: 'US',
    mapId: 'us-vegas',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/placeholder-las-p1' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/placeholder-las-p2' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/placeholder-las-p3' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/placeholder-las-q' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/placeholder-las-race' },
    ],
  },
  {
    id: 'qatar',
    name: 'Gran Premio de Qatar',
    country: 'Qatar',
    circuit: 'Circuito Internacional de Lusail',
    dates: '28-30 Nov',
    countryCode: 'QA',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/placeholder-qat-p1' },
      { name: 'Clasificación Sprint', videoUrl: 'https://video.eventoshq.me/f/placeholder-qat-sq' },
      { name: 'Carrera Sprint', videoUrl: 'https://video.eventoshq.me/f/placeholder-qat-sr' },
      { name: 'Clasificación GP', videoUrl: 'https://video.eventoshq.me/f/placeholder-qat-q' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/placeholder-qat-race' },
    ],
  },
  {
    id: 'abu-dhabi',
    name: 'Gran Premio de Abu Dhabi',
    country: 'Emiratos Árabes Unidos',
    circuit: 'Circuito Yas Marina',
    dates: '05-07 Dic',
    countryCode: 'AE',
    sessions: [
      { name: 'Práctica 1', videoUrl: 'https://video.eventoshq.me/f/placeholder-abu-p1' },
      { name: 'Práctica 2', videoUrl: 'https://video.eventoshq.me/f/placeholder-abu-p2' },
      { name: 'Práctica 3', videoUrl: 'https://video.eventoshq.me/f/placeholder-abu-p3' },
      { name: 'Clasificación', videoUrl: 'https://video.eventoshq.me/f/placeholder-abu-q' },
      { name: 'Carrera', videoUrl: 'https://video.eventoshq.me/f/placeholder-abu-race' },
    ],
  },
];